version: 2.1

executors:
  default:
    working_directory: ~/project/dimigoin-back-v2
    docker:
      - image: circleci/nodejs:latest

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  lint:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint

  build:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn run build
      - store_artifacts:
          path: ~/project/dimigoin-back-v2/dist
          destination: dist
      - persist_to_workspace:
          root: ~/
          paths:
            - project

workflows:
  lint-and-build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - lint
